// Mocks generated by Mockito 5.0.17 from annotations
// in contacts/test/core/data/repositories/contacts_repostory_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:contacts/core/data/datasources/contacts_local_datasource.dart'
    as _i3;
import 'package:contacts/core/data/models/raw_contacts_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeRawContacts_0 extends _i1.Fake implements _i2.RawContacts {}

/// A class which mocks [ContactsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactsLocalDataSource extends _i1.Mock
    implements _i3.ContactsLocalDataSource {
  MockContactsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RawContacts> fetchContacts() =>
      (super.noSuchMethod(Invocation.method(#fetchContacts, []),
              returnValue: Future<_i2.RawContacts>.value(_FakeRawContacts_0()))
          as _i4.Future<_i2.RawContacts>);
}
